#QUE ES UNA API 
"""
API - APPLICATION PROGRAMING INTERFACE,
PUNTE DE COMUNICACION ENTRE UN SERIVDOR Y UN PROGRAMA, AYUDA A PODER TRAER O ENVIAR DATOS AL SERVIDOR O PROGRAMA 
LA API USA JSON PARA PODER HABLAR CON AMBOS SERVIDOR Y PROGRAMA 

LA MAYORIA DE LAS APIS PUBLICAS Y APIS EM GENERAL TIENEN UN SITIO WEB DONDE LOS CREADORES EXPLICAN SU CONTENIO Y DATOS ALMACENADOS.
EXISTEN EN SI 3 TIPOS DE APIS:
    *PUBLICAS ABIERTAS- ESTAS NO NECESITAN NINGUN ACCESO ESPECIFICO, CUALQUIERA EN EN INTERNET PUEDE ACCEDER A SU URL.
    *PUBLICAS CON CREDENCIALES- SON GRATIS O DE PAGO  PERO SE NECESITA UN ACCESO CON REGISTRO PARA OBTENER UN TIPO DE CONTRASEÑA DE ACCESO LLAMADA API KEY
    CON ESTO SE CONTROLA QUE LA API NO SE SATURE.
    *PRIVADAS/INTERNAS- SON DE USO EXCLUSIVO PARA UN EMPRESA Y NO ESTAN INDEXADAS EN GOOGLE. 
    ESTAS PUEDEN SER DESCUBRIERTAS POR UN ATACANTE O AUDITOR HACIENDO UN RECONOCIEMIENTO, INTERCEPTANDO EL TRAFICO DE RED O LEYENDO EL CODIGO FUENTE DE UNA APLICACION WEB.

"""
#QUE ES REQUESTS 
"""
LIBRERIA DE PYTHON QUE SE USA PARA COMUNICARSE CON UN API , PERIMITE ENIVAR PETICIONES HTTP
GET PARA PEDIR INFORMACION - POST PARA ENVIAR INFORMACION EN INTERNET.

"""

#PRACTICA - PRIMERA CONSULTA A UNA API 
#HAY QUE INSTALLAR REQUESTS EN LA TEMRINAL ANTES DE PODER HACER LA CONSULTA, SE HACE CON EL COMANDO PIP INSTALL REQUEST
#SE CONSULTARA UNA API PUBLICA QUE DA LA LOCALIZACION ESPACIAL  DE LA ESTACION ESPACIAL INTERNACIONAL (ISS) EN TIEMPO REAL
import requests
#porner en una varibale la URL de la API  a usar 
url="http://api.open-notify.org/iss-now.json"

#hacer la peticion con el comando request.get() y se obtienen los datos.
respuesta=requests.get(url)

#obteniendo los datos, se traduce el JSON obtenido a un diccionario de python con .json()
datos=respuesta.json()

#mirar la informacion obtenida y traducida
print("-----DATOS OBTENIDOS-----")
print(datos)
print("-------------------------")

#como se traducen los datos a un dicionario se pueden acceder a llaves especificas

latitud=datos["iss_position"]["latitude"]
longitud=datos["iss_position"]["longitude"]
timestamp=datos["timestamp"]

print(f"EN ESTE SEGUNDO (TIMESPAMP : {timestamp}) LA ISS ESTA EN:")
print(F"LATIDUD: {latitud}")
print(F"LONGITUD: {longitud}")