#QUE ES UNA API 
"""
API - APPLICATION PROGRAMING INTERFACE,
PUNTE DE COMUNICACION ENTRE UN SERIVDOR Y UN PROGRAMA, AYUDA A PODER TRAER O ENVIAR DATOS AL SERVIDOR O PROGRAMA 
LA API USA JSON PARA PODER HABLAR CON AMBOS SERVIDOR Y PROGRAMA 

LA MAYORIA DE LAS APIS PUBLICAS Y APIS EM GENERAL TIENEN UN SITIO WEB DONDE LOS CREADORES EXPLICAN SU CONTENIO Y DATOS ALMACENADOS.
EXISTEN EN SI 3 TIPOS DE APIS:
    *PUBLICAS ABIERTAS- ESTAS NO NECESITAN NINGUN ACCESO ESPECIFICO, CUALQUIERA EN EN INTERNET PUEDE ACCEDER A SU URL.
    *PUBLICAS CON CREDENCIALES- SON GRATIS O DE PAGO  PERO SE NECESITA UN ACCESO CON REGISTRO PARA OBTENER UN TIPO DE CONTRASEÑA DE ACCESO LLAMADA API KEY
    CON ESTO SE CONTROLA QUE LA API NO SE SATURE.
    *PRIVADAS/INTERNAS- SON DE USO EXCLUSIVO PARA UN EMPRESA Y NO ESTAN INDEXADAS EN GOOGLE. 
    ESTAS PUEDEN SER DESCUBRIERTAS POR UN ATACANTE O AUDITOR HACIENDO UN RECONOCIEMIENTO, INTERCEPTANDO EL TRAFICO DE RED O LEYENDO EL CODIGO FUENTE DE UNA APLICACION WEB.

"""
#QUE ES REQUESTS 
"""
LIBRERIA DE PYTHON QUE SE USA PARA COMUNICARSE CON UN API , PERIMITE ENIVAR PETICIONES HTTP
GET PARA PEDIR INFORMACION - POST PARA ENVIAR INFORMACION EN INTERNET.

"""

#PRACTICA - PRIMERA CONSULTA A UNA API 
#HAY QUE INSTALLAR REQUESTS EN LA TEMRINAL ANTES DE PODER HACER LA CONSULTA, SE HACE CON EL COMANDO PIP INSTALL REQUEST
#SE CONSULTARA UNA API PUBLICA QUE DA LA LOCALIZACION ESPACIAL  DE LA ESTACION ESPACIAL INTERNACIONAL (ISS) EN TIEMPO REAL
import requests
#porner en una varibale la URL de la API  a usar 
url="http://api.open-notify.org/iss-now.json"

#hacer la peticion con el comando request.get() y se obtienen los datos.
respuesta=requests.get(url)

#obteniendo los datos, se traduce el JSON obtenido a un diccionario de python con .json()
datos=respuesta.json()

#mirar la informacion obtenida y traducida
print("-----DATOS OBTENIDOS-----")
print(datos)
print("-------------------------")

#como se traducen los datos a un dicionario se pueden acceder a llaves especificas

latitud=datos["iss_position"]["latitude"]
longitud=datos["iss_position"]["longitude"]
timestamp=datos["timestamp"]

print(f"EN ESTE SEGUNDO (TIMESPAMP : {timestamp}) LA ISS ESTA EN:")
print(F"LATIDUD: {latitud}")
print(F"LONGITUD: {longitud}")

#COMO ENVIAR DATOS A UNA API 
"""
SE USA EL METODO .POST() Y DENTRO DE ESTE SE PONE: LA URL DE LA API Y   COMANDO JSON= EL DICCIONARIO CON LOS DATOS A ENVIAR 

"""

#PRACTICA

#USO DE UNA API PUBLICA QUE SIRVE PARA POBRAR ENVIOS
url_api="https://httpbin.org/post"

datos_enviar={
    "usuario":"analista_seguridad",
    "evento":"Intento de intrusion detectado",
    "ip_origen":"192.168.1.105"
}

#USO DEL COMANDO .POST() PARA EL ENVIO DE DATOS A LA API

envio=requests.post(url_api,json=datos_enviar)

#RESPUESTA DEL SERVIDOR DICIENDO QUE RECIBIO LOS DATOS 
print(respuesta.json())

#FUNCIONAMIENTO EN APIS PRIVADAS 
"""
PARA PODER CONECTAR UNA API A UNA EMPRESA (EJEMPLO: BANCO DE CRIPTOMONEDAS COMO COINBASE) PARA VER TU SALDO O HACER TRANSACIONES AUTOMATICAMENTE, 
SE HACE CON CAPA DE SEGURIDAD OBLIGATORIA (LA AUTENTICACION DE CREDENCIALES), PARA QUE A ESTOS DATOS EN LA API SEAN PROTEGIDOS SE EXIGEN DOS COSAS:
APIKEY (LLAVE PUBLICA): NOMBRE DE USUARIO  Y API SECRET : CONTRASEÑA DE USUARIO

"""
#EJEMPLO
"""
import request 
url="https://api.tu-criptobanca.com/v1/mi_balance"

#credenciales de seguridad administradas por la empresa
HEADERS_DE_SEGURIDAD = {
                        "X-XBT-API-KEY" :"API_KEY"
                        "X-XBT-API-SIGN":"CONTRASEÑA"
}

# SE PASA LA URL Y HEADERS CON PERMISOS
respuesta=requests.get(url,headers=HEADERS_DE_SEGURIDAD)

#SI LAS LLAVES SON CORRECTAS DEVOLVERA LOS DATOS SOLICITADOS
print(respuesta.json())
"""